### ISSUE TITLE
App crashes if the CordovaActivity is stopped during scanning

### ISSUE THREAD

**Issue by mbektchiev** [Telerik-Verified-Plugins/BarcodeScanner#26]
Steps to reproduce:

* Turn on the `Developer options | Don't keep activities` to force stopping of the main activity as soon as the new one is launched
* Open the sample app and scan
* Hit the back button or scan a QR code

=> Result: 
```
java.lang.NullPointerException
at com.phonegap.plugins.barcodescanner.BarcodeScanner.onActivityResult(BarcodeScanner.java:208)
at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:353)
at android.app.Activity.dispatchActivityResult(Activity.java:5423)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3347)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2761) 
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238) 
at android.app.ActivityThread.access$800(ActivityThread.java:135) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5001) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by EddyVerbruggen** [comment]
Hey Martin,

Is there a valid reason for folks to mess with that developer setting? I really doubt if one should expect apps to not break when that default is changes.

If CordovaActivity is killed then even if we could recreate it it would never be restored to the same place the user started the scan... I'm not sure we should even try to fix this.

Similar issue in the upstream repo: https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/74

**Comment by mbektchiev** [comment]
This option just helps in making it easier to reproduce the issue. I think that some real world scenarios can also cause the system to stop the activity - maybe switching to other apps that require lots of memory while barcode scanner is active. Since the original plugin authors do not consider this as a problem, then we can leave it as is.

**Comment by EddyVerbruggen** [comment]
Hey Martin, makes sense, I didn't realise you were doing that to help me reproducing the issue.

As the webview gets recreated after scanning it has no cordova callback context anymore so I don't see an easy way to transparently pass the scanresult back to the webview, but I've changed the native side so it no longer crashes your app.
